[workspace]
members = ["ir-explorer","ir", "lsp", "parser", "runtime", "cl_backend"]

[package]
name = "neruda"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
arena = { git = "https://github.com/antosatko/arena" }
ruparse = { git = "https://github.com/antosatko/ruparse" }
smol_str = { version = "0.3.5" }
arena-scope = { git = "https://github.com/antosatko/arena-scope" }

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
parser = { path = "parser" }
ir = { path = "ir" }
cl_backend = { path = "cl_backend" }
