[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

# serde_json for testing
[dev-dependencies]
bincode = "1.3"
serde_json = "1.0"
anyhow = "1.0"
peak_alloc = "0.2.1"
# miniz_oxide = "0.7.3" # compression tool