[package]
name = "neruda_ast"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
ruparse = { path = "../ruparse", features = ["serde"]}
serde = { version = "*", features = ["derive"] }
serde_json = "*"
